name: Eggs Test

on: 
  push:
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [macOS-latest, windows-latest, ubuntu-latest]

    steps:
      - name: Setup repository
        uses: actions/checkout@v2

      - name: Setup Deno
        uses: denolib/setup-deno@master

      - name: "test: eggs link"
        run: deno run --unstable -A eggs/mod.ts link --key ${{ secrets.NESTAPIKEY }}

      - name: "test commands"
        run: deno test --unstable -A eggs/tests/commands
